name: Space Deploy

on:
    push:
        branches:
            - "master"

env:
    PYTHON: 3.11

jobs:
    deploy:
        defaults:
            run:
                shell: bash

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install Space
              run: |
                  curl -fsSL https://get.deta.dev/space-cli.sh | sh
                  echo "$HOME/.detaspace/bin" >> $GITHUB_PATH
                  echo "SPACE_ACCESS_TOKEN=${{ secrets.SPACE_ACCESS_TOKEN }}" >> $GITHUB_ENV

            - name: Deploy
              run: |
                  space link --id ${{ secrets.SPACE_PROJECT_ID }}
                  space push
